---
title: "Financial & Legal Resources"
---

This page contains resources related to finance, income, Healthcare Benefits and more.


PA UNEMPLOYEMENT BENEFITS

INFORMATION FOR PENNSYLVANIA EMPLOYEES IMPACTED BY COVID-19

If you are employed in Pennsylvania and are unable to work because of Coronavirus disease (COVID-19), you may be eligible for Unemployment or Workers' Compensation benefits. The Department of Labor & Industry will continue to provide important employment benefit updates as the situation evolves.

You may be eligible if:

Your employer temporarily closes or goes out of business because of COVID-19
Your employer reduces your hours because of COVID-19
You have been told not to work because your employer feels you might get or spread COVID-19
You have been told to quarantine or self-isolate, or live/work in a county under government-recommended mitigation efforts

 Apply:  https://tinyurl.com/PA-UnEmp-Apply



INDEPENDENT CONTRACTORS/GIG WORKERS

Pennsylvania's new Pandemic Unemployment Assistance (PUA) website for self-employed, independent contractors, gig workers, and others not eligible for regular unemployment compensation (UC) will begin accepting applications within the next few days. PUA is included in the new federal unemployment compensation benefits provided by the CARES Act.

https://tinyurl.com/PA-Pandemic-Unemployment-Assis


HEALTHCARE

If you lost your job due to COVID19, you can enroll in the Affordable Care Act for health insurance.

If you've lost health insurance because of COVID-19,  quit or got fired from a job, you have 60 days to enroll in the federal exchanges of the Affordable Care Act by going to www.healthcare.gov.

The Pennsylvania Attorney General's Office is fighting for U.S. Department of Health & Human Services to reopen ACA enrollment for ALL people. 
But right now, if you are unemployed, you CAN enroll. https://www.healthcare.gov/


LEGAL SERVICES

Philadelphia Legal Assistance:

https://tinyurl.com/PHL-Legal 

For more than 20 years, Philadelphia Legal Assistance (PLA) has provided free civil legal assistance to low-income individuals and families in Philadelphia.
About 30% of the people in Philadelphia live in families with incomes below the federal poverty level.  For those who are low-income, elderly, or disabled, our legal assistance is often crucial for them to protect their homes, their children, their safety, and their livelihood.  PLA is dedicated to helping those who cannot afford legal counsel navigate the legal system and understand and safeguard their rights.

Community Legal Services

https://clsphila.org/coronavirus/

Community Legal Services (CLS) has provided free civil legal assistance to more than one million low-income Philadelphians. Approximately 10,000 clients were represented by CLS in the past year. CLS assists clients when they face the threat of losing their homes, incomes, health care, and even their families. CLS attorneys and other staff provide a full range of legal services, from individual representation to administrative advocacy to class action litigation, as well as community education and social work. CLS is nationally recognized as a model legal services program.


