---
title: "Food & Livelihood "
---

RESOURCES FOR SENIORS

If you or a loved one is 60+ and struggling to obtain food, The Philadelphia Corporation of Aging has pick up and delivery resources available.

For more information on delivery, call 215-765-9040 or visit: https://www.pcacares.org/


FOR ALL PHILADELPHIANS

Many Philadelphians are in need of free food due to school closures, loss of income, or other challenges caused by COVID-19. In response to this need, the City of Philadelphia and partners have developed two ways for residents to find free food:

1) Food sites where any resident can pick up free food for their household. 
2) Student meal sites where any child can pick up free meals.

About the food sites:

Sites are open Mondays and Thursdays from 10 a.m. – 12 p.m.
Residents can pick up one box per household. 
Boxes contain non-perishable items on Mondays and fresh produce on Thursdays.
Residents do not need to present an ID or proof of income for eligibility.
Food sites are supported by the City, Share Food Program, and Philabundance.
These food sites are supplementary to the existing food pantry network. 

To find a food pantry closest to you, call 311.
Additional information can be found at: 
https://tinyurl.com/PHL-Food 





 

