---
title: "Legal"
---



LEGAL SERVICES

Philadelphia Legal Assistance:

https://tinyurl.com/PHL-Legal 

For more than 20 years, Philadelphia Legal Assistance (PLA) has provided free civil legal assistance to low-income individuals and families in Philadelphia.
About 30% of the people in Philadelphia live in families with incomes below the federal poverty level.  For those who are low-income, elderly, or disabled, our legal assistance is often crucial for them to protect their homes, their children, their safety, and their livelihood.  PLA is dedicated to helping those who cannot afford legal counsel navigate the legal system and understand and safeguard their rights.

Community Legal Services

https://clsphila.org/coronavirus/

Community Legal Services (CLS) has provided free civil legal assistance to more than one million low-income Philadelphians. Approximately 10,000 clients were represented by CLS in the past year. CLS assists clients when they face the threat of losing their homes, incomes, health care, and even their families. CLS attorneys and other staff provide a full range of legal services, from individual representation to administrative advocacy to class action litigation, as well as community education and social work. CLS is nationally recognized as a model legal services program.



